// ── Core Data Types ──

export interface Course {
  id: string;
  name: string;
  description: string;
  semester: string;
  learnusId: string; // LearNUS course ID for dedup
  learnusUrl: string;
  topics: CourseTopic[];
  weekly_schedule: WeeklyTopic[];
  created_at: string;
  updated_at: string;
}

export interface CourseTopic {
  id: string;
  name: string;
  description: string;
  week: number;
  subtopics: string[];
  mastery: number; // 0-100
}

export interface WeeklyTopic {
  week: number;
  title: string;
  topics: string[];
  objectives: string[];
}

export interface Material {
  id: string;
  courseId: string;
  filename: string;
  fileType: "pdf" | "pptx" | "docx" | "hwp" | "text" | "image" | "other";
  contentText: string;
  learnusUrl: string;
  downloadedAt: string;
}

// ── Assignment Workflow ──

export type AssignmentStatus =
  | "new" // Just detected from LearNUS
  | "drafting" // AI is generating a draft
  | "draft_ready" // Draft generated, needs review
  | "reviewed" // Student has reviewed/edited
  | "submitted"; // Student submitted on LearNUS

export interface Assignment {
  id: string;
  courseId: string;
  courseName: string;
  learnusId: string; // For dedup on re-sync
  learnusUrl: string; // Direct link for submission
  title: string;
  instructions: string;
  type: "assignment" | "quiz" | "essay" | "project" | "other";
  dueDate: string | null;
  status: AssignmentStatus;
  draftSolution: string; // Auto-generated by AI
  finalSolution: string; // After student edits
  attachments: string[]; // Filenames from LearNUS
  detectedAt: string;
  draftedAt: string | null;
  submittedAt: string | null;
}

// ── Activity Feed ──

export type ActivityType =
  | "assignment"
  | "material"
  | "announcement"
  | "grade"
  | "quiz";

export interface Activity {
  id: string;
  type: ActivityType;
  courseId: string;
  courseName: string;
  title: string;
  description: string;
  url: string;
  read: boolean;
  handled: boolean; // True once auto-drafted or ingested
  detectedAt: string;
  dueDate: string | null;
}

// ── Sync State ──

export interface SyncState {
  lastSyncedAt: string | null;
  inProgress: boolean;
  phase: SyncPhase;
  message: string;
  coursesFound: number;
  assignmentsFound: number;
  materialsFound: number;
}

export type SyncPhase =
  | "idle"
  | "logging_in"
  | "scraping_courses"
  | "scraping_assignments"
  | "scraping_materials"
  | "processing"
  | "auto_drafting"
  | "complete"
  | "error";

// ── Chat ──

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}

// ── Quiz ──

export interface QuizQuestion {
  id: string;
  question: string;
  type: "multiple_choice" | "short_answer" | "true_false";
  options: string[];
  correct_answer: string;
  explanation: string;
  difficulty: "easy" | "medium" | "hard";
  topic: string;
}

// ── Study Plan ──

export interface StudyPlan {
  plan_type: "regular" | "cram";
  total_days: number;
  days: StudyDay[];
}

export interface StudyDay {
  date: string;
  topics: string[];
  tasks: string[];
  estimated_hours: number;
  is_review: boolean;
}

// ── Settings ──

export interface Settings {
  aiProvider: "claude" | "chatgpt";
  learnusCredentials: {
    username: string;
    password: string;
  } | null;
  autoSyncOnOpen: boolean;
  syncIntervalMinutes: number;
}

export const DEFAULT_SETTINGS: Settings = {
  aiProvider: "claude",
  learnusCredentials: null,
  autoSyncOnOpen: true,
  syncIntervalMinutes: 0, // 0 = disabled
};
